# Generated by Django 3.1.7 on 2021-04-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='  tbl_posts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='tbl_users',
        ),
    ]
